### ISSUE TITLE
POST for client Erroring Out

### ISSUE THREAD

**Issue by timothyk7** [classy-org/classy-pay-client#6]
StackTrace:
`
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at getResult (/Users/tkua/Desktop/bug_triage/node_modules/classy-pay-client/index.js:44:12)
    at Request.<anonymous> (/Users/tkua/Desktop/bug_triage/node_modules/classy-pay-client/index.js:52:21)
    at Request._callback (/Users/tkua/Desktop/bug_triage/node_modules/lodash/lodash.js:10067:25)
    at Request.requestRetryReply [as reply] (/Users/tkua/Desktop/bug_triage/node_modules/requestretry/index.js:105:19)
    at Request.<anonymous> (/Users/tkua/Desktop/bug_triage/node_modules/requestretry/index.js:133:10)
    at Request.self.callback (/Users/tkua/Desktop/bug_triage/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/tkua/Desktop/bug_triage/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/tkua/Desktop/bug_triage/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
`

console.log from POST before getResult
`  body:
   { createdDate: '2017-12-13T23:49:35.000Z',
     id: '922337203685477605',
     name: 'classy ach',
     calcMethod: 'FIXED',
     fee: 1,
     paymentMethod: 'ACH',
     iteration: 'ALL',
     appId: '12',
     status: 'ACTIVE' },
  attempts: 1 }
...
undefined:1
[object Object]`

**Comment by morgansierrasnyder** [comment]
I've also run into this issue. Here's an example of the request and error output when I hit the classy-pay-client `post` method to update recurring settings:

```
Classy Pay: request {
    "debugId": 13,
    "uri": "https://staging-pay.stayclassy.org/recurring/922337203685499352?appId=1673&meta=true",
    "method": "POST",
    "headers": {
        "Authorization": <hidden>,
        "User-Agent": "ClassyPay Node.JS",
        "host": "staging-pay.stayclassy.org",
        "accept": "application/json",
        "content-type": "application/json",
        "content-length": 400
    },
    "body": {
        "firstName": "John",
        "lastName": "Doe",
        "email": "{{email}}",
        "address1": "00 Acme Dr",
        "city": "Acme City",
        "state": "CA",
        "zip": "12345",
        "country": "US",
        "currency": "USD",
        "amount": 10,
        "type": "DONATION",
        "recurringUnit": "MONTHLY",
        "recurUntil": "2020-01-01T00:00:00Z",
        "recurOn": 12,
        "paymentMethod": "CC",
        "paymentDetails": {
            "token": "4012008343230026",
            "cvv": "123",
            "expirationMonth": "09",
            "expirationYear": 2019
        },
        "fot": false
    }
}
undefined:1
[object Object]
 ^

SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Classy.onRequestDebug [as requestDebugAction] (/Users/msnyder/Development/classyql/lib/server.js:63:108)
    at /Users/msnyder/Development/classyql/node_modules/classy-node/dist/ClassyResource/main.js:85:23
    at Request.<anonymous> (/Users/msnyder/Development/classyql/node_modules/request-debug/index.js:55:13)
    at emitTwo (events.js:111:20)
    at Request.emit (events.js:194:7)
    at Request.<anonymous> (/Users/msnyder/Development/classyql/node_modules/request/request.js:1044:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:191:7)
    at IncomingMessage.<anonymous> (/Users/msnyder/Development/classyql/node_modules/request/request.js:965:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error Command failed with exit code 1.
```
